### ISSUE TITLE
Docker image fails to start

### ISSUE THREAD

**Issue by cstranex** [readthedocs/ethical-ad-server#251]
Trying to start the docker hub image fails. The logs indicate the Django debug toolbar is not present:
```
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'debug_toolbar'
```

**Comment by ericholscher** [comment]
I'd recommend using the instructions in our docs to start the server, not the docker hub image: https://ethical-ad-server.readthedocs.io/en/latest/

**Comment by davidfischer** [comment]
This error looks like you're using the Docker image which is built for production but relying on the development settings. Not all of the development packages are installed in the image. Instead the production requirements are installed.

**Comment by cstranex** [comment]
Thanks, looks like you need to set the `DJANGO_SETTINGS_MODULE` otherwise it will default to `config.settings.debug` instead of `config.settings.production`.

Btw, might be worth having an example of running with a docker-compose.yml :
```
version: "3"

services:
   adserver:
      image: readthedocs/ethicaladserver
      environment:
        SECRET_KEY: *****
        DATABASE_URL: psql://ad:ad@postgres/ad
        ALLOWED_HOSTS: localhost
        REDIS_URL: redis://redis:6379/0
        DJANGO_SETTINGS_MODULE: config.settings.production
        SENDGRID_API_KEY: *****
      ports:
        - 5000:5000
        - 2222:2222
   postgres:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=ad
        - POSTGRES_USER=ad
   redis:
      image: redis
```
